server:
  servlet:
    context-path: /
  port: 13080

spring:
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: asdf

kakao:
  rest-api-host: https://dapi.kakao.com
  rest-api-key: 8faed6b62733ecf33cfcbc9b78224a2c